<?php
namespace Processus\Lib\Profiler;


require_once '/Users/francis/www/shakeonit/library/Processus/core/Lib/Profiler/ProcessusProfiler.php';

/**
 * Test class for ProcessusProfiler.
 * Generated by PHPUnit on 2012-01-03 at 10:44:13.
 */
class ProcessusProfilerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ProcessusProfiler
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ProcessusProfiler;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testGetInstance().
     */
    public function testGetInstance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testAddDebugInfo().
     */
    public function testAddDebugInfo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testApplicationProfilerStart().
     */
    public function testApplicationProfilerStart()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testApplicationProfilerEnd().
     */
    public function testApplicationProfilerEnd()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testApplicationDuration().
     */
    public function testApplicationDuration()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testGetProfilerStack().
     */
    public function testGetProfilerStack()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
